boot_list = [
    "anklet", "boots", "clogs", "feet", "footguards", "footpads",
    "footsteps", "footwraps", "greatboots", "greaves", "heels", "sabatons",
    "sandals", "slippers", "sneakers", "socks", "sprinters", "spurs",
    "stompers", "treads", "walkers", "warboots", "wraps", "zoomers"]

body_list = [
    "banded mail", "battleplate", "bone armor", "chestguard", "chestpiece", "chestplate",
    "coat", "cuirass", "garments", "gown", "great plate", "jacket",
    "jerkin", "mail", "raiment", "raiment", "robes", "shirt",
    "suit", "tanktop", "tunic", "vest", "vestment"]

gauntlet_list = [
    "fists", "gauntlets", "gloves", "grips", "handguards", "handguards",
    "hands", "knuckles", "mittens", "warfists", "wraps"]

helmet_list = [
    "armet", "aventail", "barbute", "bascinet", "cap", "close helmet",
    "duster", "enclosed helmet", "facemask", "falling buffe", "frog-mouth helm", "goggles",
    "great helm", "hat", "helm", "helmet", "kabuto", "kettle hat",
    "nasal helmet", "sallet", "shorwell helmet", "spangenhelm", "turban helmet", "visor",
    "wrap"]

leg_list = [
    "bone greaves", "breeches", "breeches", "dress", "greaves",
    "kilt", "leggings", "legguards", "legplates", "legwraps", "pants",
    "platelegs", "robes", "shorts", "skirt", "tassets", "trousers"]

shield_list = [
    "buckler", "enarmes", "greatshield", "gulge", "heater shield", "kite shield",
    "mantlet", "pavise", "rondache", "shield boss", "targe", "wall",
    "ward"]

creature_list = [
    "Aatxe", "Abaia", "Abarimon", "Abath",
    "Abura-sumashi", "Acephali", "Achlis", "Adar Llwch Gwin", "Adhene", "Adlet",
    "Aerico", "Afanc", "Agathodaemon", "Agloolik", "Agni", "Agogwe",
    "Ahkiyyini", "Ahura", "Airavata", "Aitu", "Aitvaras", "Ajatar",
    "Akhlut", "Akkorokamui", "Akurojin-no-hi", "Al Rakim", "Al-mi'raj", "Ala",
    "Alal", "Alicanto", "Alkonost", "Allocamelus", "Alphyn", "Alseid",
    "Alux", "Alû", "Amanojaku", "Amarum", "Amazake-babaa", "Amemasu",
    "Ammit", "Amorōnagu", "Amphiptere", "Amphisbaena", "Anakim", "Angel",
    "Ani Hyuntikwalaski", "Ankou", "Anqa", "Antaeus", "Antero Vipunen", "Anubis",
    "Anzû", "Ao Ao", "Aobōzu", "Apkallu", "Argus Panoptes", "Arikura-no-baba",
    "Arimaspi", "Arkan Sonney", "Asag", "Asanbosam", "Asena", "Ashi-magari",
    "Aspidochelone", "Asrai", "Astomi", "Asura", "Aswang", "Atomy",
    "Atshen", "Auloniad", "Avalerion", "Azukiarai", "Baba Yaga", "Badalisc",
    "Bahamut", "Bai Ze", "Bake-kujira", "Bakeneko", "Bakezōri", "Bakunawa",
    "Balaur", "Baloz", "Bannik", "Banshee", "Bar Juchne", "Barbegazi",
    "Bardha", "Barghest", "Basajaun", "Bashe", "Basilisco Chilote", "Basilisk",
    "Bathala", "Batibat", "Baykok", "Beast of Bray Road", "Behemoth", "Bennu",
    "Bestial beast", "Bestiary", "Bestiary", "Bestiary", "Bies", "Bigfoot",
    "Bishop-fish", "Biwa", "Black Annis", "Black Shuck", "Blafard", "Bloody Bones",
    "Blue Crow", "Bluecap", "Bodach", "Bogeyman", "Boggart", "Bogle",
    "Bolla", "Bonnacon", "Boo Hag", "Boobrie", "Broxa", "Buckriders",
    "Bugbear", "Buggane", "Bugul Noz", "Bukavac", "Bunyip", "Buraq",
    "Byangoma", "Bysen", "Błudnik", "Cabeiri", "Cacus", "Cadejo",
    "Cailleach", "Caipora", "Caladrius", "Calydonian Boar", "Calygreyhound", "Camahueto",
    "Cambion", "Campe", "Canotila", "Caoineag", "Catoblepas", "Ceffyl Dŵr",
    "Centaur", "Central America", "Cerastes", "Cerberus", "Cercopes", "Ceryneian Hind",
    "Cetan", "Chamrosh", "Chaneque", "Changeling", "Charybdis", "Chepi",
    "Cherufe", "Cheval Gauvin", "Cheval Mallet", "Chickcharney", "Chindi", "Chinthe",
    "Chollima", "Chonchon", "Chromandi", "Chrysaor", "Chupacabra", "Churel",
    "Ciguapa", "Cihuateteo", "Cikavac", "Cinnamon bird", "Cipactli", "Coblynau",
    "Cockatrice", "Corycian Cave", "Cretan Bull", "Crinaeae", "Crocotta", "Cuegle",
    "Curupira", "Cuélebre", "Cyhyraeth", "Cynocephaly", "Căpcăun", "Cŵn Annwn",
    "Daitya", "Daphnaie", "Datsue-ba", "Dead Sea Apes", "Ded Moroz", "Deer",
    "Deer Woman", "Deity", "Demigod", "Dhampir", "Di Penates", "Di sma undar jordi",
    "Dilong", "Dipsa", "Dirawong", "Diwata", "Djall", "Dokkaebi",
    "Doppelgänger", "Dragon", "Dragon turtle", "Drangue", "Draugr", "Drekavac",
    "Drude", "Druk", "Dryad", "Dullahan", "Dvorovoi", "Dybbuk",
    "DzunukwaSamebito", "Easter Bilby", "Easter Bunny", "Edimmu", "Egbere", "Einherjar",
    "Eleionomae", "Elemental", "Elf", "Eloko", "Emere", "Empusa",
    "Engkanto", "Ent", "Epimeliad", "Erchitu", "Erinyes", "Erlking",
    "Erymanthian Boar", "EtiäinenDahu", "Fafnir", "Fairy", "Familiar spirit", "Far darrig",
    "Faun", "Fear gorta", "Fenghuang", "Fenodyree", "Fenrir", "Fext",
    "Finfolk", "Fir Bolg", "Fish-man", "Fomorians", "Forest Bull", "Freybug",
    "Fuath", "Funayūrei", "Futakuchi-onna", "FylgjaGaasyendietha", "Gagana", "Gallu",
    "Gamayun", "Gana", "Gancanagh", "Gandaberunda", "Gandharva", "Garmr",
    "Garuda", "Gashadokuro", "Gaueko", "Geb", "Gegenees", "Genius loci",
    "Geryon", "Ghillie Dhu", "Ghost", "Ghoul", "Gigelorum", "Gjenganger",
    "Glaistig", "Glashtyn", "Gnome", "Goblin", "God", "Gog and Magog",
    "Gold-digging ant", "Golem", "Gorgades", "Gorgon", "Goryō", "Gremlin",
    "Griffin", "Grindylow", "Gualichu", "Guardian angel", "Gulon", "Gurumapa",
    "Gwyllgi", "Gwyllion", "Gytrash", "Hades", "Hadhayosh", "Hag",
    "Haietlik", "Half-elf", "Haltija", "Hamadryad", "Hamingja", "Hanau epe",
    "Hantu Air", "Hantu Raya", "Harionago", "Harpy", "Headless Horseman", "Headless Mule",
    "Heikegani", "Heinzelmännchen", "Hellhound", "Heracles", "Hercinia", "Herensuge",
    "Hesperides", "Hidebehind", "Hiderigami", "Hieracosphinx", "Hiisi", "Hippogriff",
    "Hippopodes", "Hircocervus", "Hitodama", "Hitotsume-kozō", "Hobbididance", "Hobgoblin",
    "Hodag", "Hombre Gato", "Homunculus", "Hoop snake", "Hoopoe", "Horned Serpent",
    "Hotoke", "Houri", "Huldufólk", "Huli jing", "Humbaba", "Hundun",
    "Hupia", "Hypnalis", "Hākuturi", "Iannic-ann-ôd", "Ibong Adarna", "Iele",
    "Ifrit", "Ikiryō", "Iku-Turso", "Imp", "Inapertwa", "Indrik",
    "Inkanyamba", "Inugami", "Ipotane", "Iratxoak", "Isonade", "Ittan-momen",
    "Jack-o'-lantern", "Jackalope", "Jaculus", "Jatayu", "Jenglot", "Jengu",
    "Jentil", "Jenu", "Jersey Devil", "Jiangshi", "Jiaolong", "Jikininki",
    "Jinn", "Jogah", "Jorōgumo", "Jumbee", "Jörmungandr", "Jötunn",
    "Kabouter", "Kachina", "Kalakeyas", "Kamaitachi", "Kami", "Kangla Palace",
    "Kappa", "Kapre", "Karkadann", "Karura", "Karzełek", "Kasa-obake",
    "Ke'lets", "Kee-wakw", "Keelut", "Kelpie", "Keukegen", "Kholomodumo",
    "Kigatilik", "Kikimora", "Kin-u", "Kinnara", "Kitsune", "Kitsune",
    "Kiyohime", "Klabautermann", "Knucker", "Kobalos", "Kobold", "Komainu",
    "Koro-pok-guru", "Korrigan", "Kraken", "Krampus", "Krasnoludek", "Krasue",
    "Kubikajiri", "Kuchisake-onna", "Kuda-gitsune", "Kumakatok", "Kumiho", "Kupua",
    "Kurma", "Kurupi", "Kushtaka", "La Llorona", "Labbu", "Laestrygonians",
    "Lakanica", "Lake monster", "Lakhey", "Lamassu", "Lambton Worm", "Landvættir",
    "Lares", "Latin America", "Lauma", "Lava bear", "Lavellan", "Leontophone",
    "Leprechaun", "Leviathan", "Leyak", "Lidérc", "Likho", "Lilin",
    "Lilith", "Lilith", "Lindworm", "Ljubi", "Loch Ness Monster", "Lou Carcolh",
    "Lubber fiend", "Luduan", "Lugat", "Luison", "Lusca", "Lutin",
    "Maa-alused", "Machlyes", "Macrocephali", "Maero", "Mairu", "Majitu",
    "Mallt-y-Nos", "Mami Wata", "Manananggal", "Mandragora", "Manes", "Mannegishi",
    "Manticore", "Manx people", "Mapinguari", "Marabbecca", "Mareikura", "Mares of Diomedes",
    "Marid", "Marmennill", "Matagot", "Matsya", "Mazzikin", "Mbwiri",
    "Mbói Tu'ĩ", "Medusa", "Meliae", "Melusine", "Menehune", "Menninkäinen",
    "Merlin", "Merlion", "Mermaid", "Merman", "Merman", "Merrow",
    "Minka Bird", "Minokawa", "Minotaur", "Mizuchi", "Mohan", "Mokoi",
    "Mono Grande", "Mooinjer veggey", "Moroi", "Moss people", "Moñái", "Mujina",
    "Muldjewangk", "Muma Pădurii", "Mummy", "Muscaliet", "Musimon", "Myling",
    "Myrmecoleon", "Nachzehrer", "Nagual", "Naiad", "Namahage", "Napaeae",
    "Narasimha", "Nargun", "Nariphon", "Nasnas", "Nawao", "Negret",
    "Nekomata", "Nephilim", "Nereid", "Nereus", "Ngen", "Nguruvilu",
    "Nian", "Nightmarchers", "Nimerigar", "Ningyo", "Ninki Nanka", "Nocnitsa",
    "Noppera-bō", "Nuckelavee", "Nue", "Nuku-mai-tore", "Nuli", "Numen",
    "Nuno sa punso", "Nurarihyon", "Nure-onna", "Nyami Nyami", "Nymph", "Näkki",
    "Níðhöggr", "Nāga", "Obake", "Obayifo", "Oceanus", "Odei",
    "Og", "Ogopogo", "Ogre", "Ogun", "Ojáncanu", "Okuri-inu",
    "Onocentaur", "Onoskelis", "Onryō", "Onza", "Oozlum bird", "Ophiotaurus",
    "Orang Minyak", "Oread", "Orobas", "Orphan Bird", "Orthrus", "Oshun",
    "Osiris", "Otso", "Ouroboros", "Ovinnik", "Paasselkä devils", "Pamola",
    "Panis", "Panotti", "Parandrus", "Patagon", "Patagonia", "Patasola",
    "Pegaeae", "Pegasus", "Pelesit", "Peluda", "Penanggalan", "Penghou",
    "Peri", "Peryton", "Pesanta", "Peuchen", "Phi Tai Hong", "Phoenicia",
    "Piasa", "Pictish Beast", "Pillan", "Pishacha", "Pixie", "Pixiu",
    "Polevik", "Polong", "Poltergeist", "Pombero", "Ponaturi", "Poukai",
    "Preta", "Pricolici", "Psoglav", "Psotnik", "Psychai", "Psychopomp",
    "Pugot", "Pyrausta", "Púca", "Qalupalik", "Qilin", "Qiqirn",
    "Qliphoth", "Questing Beast", "Quetzalcoatl", "Quinotaur", "Rabisu", "Radande",
    "Raijū", "Rainbow Serpent", "Rainbow crow", "Rakshasa", "Ramidreju", "Raróg",
    "Ratatoskr", "Raven Mocker", "Redcap", "Reichsadler", "Rephaite", "Reptilian humanoid",
    "Robin Hood", "Rokurokubi", "Rompo", "Rougarou", "Rusalka", "Rå",
    "Sampati", "Sandman", "Santa Claus", "Santelmo", "Sarimanok", "Satan",
    "Satyr", "Sazae-oni", "Scitalis", "Scylla", "Sea monk", "Sea monster",
    "Sea serpent", "Selkie", "Serpent", "Serpopard", "Shachihoko", "Shaitan",
    "Shark", "Shedim", "Shellycoat", "Shenlong", "Shikigami", "Shikoku",
    "Shikome", "Shinigami", "Shisa", "Shtriga", "Shug Monkey", "Si-Te-Cah",
    "Sigbin", "Silenus", "Simargl", "Simurgh", "Sirin", "Sisiutl",
    "Skin-walker", "Skookum", "Skrzak", "Sleipnir", "Sleipnir", "Sluagh",
    "Soucouyant", "Spearfinger", "Sphinx", "Spirit", "Spriggan", "Squonk",
    "Stihi", "Strigoi", "Struthopodes", "Strzyga", "Stuhać", "Stymphalian birds",
    "Suangi", "Succubus", "Svartálfar", "Svaðilfari", "Swan maiden", "Sylph",
    "Syrbotae", "Syrictæ", "Sânziană", "Takam", "Talos", "Tangie",
    "Taniwha", "Taotao Mona", "Taotie", "Taotie", "Tapairu", "Tarasque",
    "Tartalo", "Tartaruchi", "Tatami", "Tavara", "Teju Jagua", "Tengu",
    "Tengu", "Tennin", "Tepegoz", "Terrible Monster", "Teumessian fox", "Theriocephaly",
    "Tiangou", "Tianlong", "Tibicena", "Tiddy Mun", "Tigmamanukan", "Tikbalang",
    "Tikoloshe", "Timingila", "Tipua", "Tiyanak", "Tizheruk", "Tlahuelpuchi",
    "Tlaxcaltec", "Tofu", "Topielec", "Toyol", "Trauco", "Trenti",
    "Trickster", "Tripura", "Tripurasura", "Troll", "Tsuchigumo", "Tsuchinoko",
    "Tsukumogami", "Tsul 'Kalu", "Tsurube-otoshi", "Tupilaq", "Turul", "Tylwyth Teg",
    "Typhon", "Tzitzimitl", "Türst", "Ubume", "Uchek Langmeidong", "Umibōzu",
    "Undead", "Underwater panther", "Undine", "Unhcegila", "Unicorn", "Urayuli",
    "Uriaș", "Urmahlullu", "Ushi-oni", "Uwan", "Vahana", "Valkyrie",
    "Valravn", "Vampire", "Vanara", "Varaha", "Vardøger", "Vetala",
    "Vishnu", "Vision Serpent", "Vodyanoy", "Vrykolakas", "Vâlvă", "Vântoase",
    "Vættir", "Víðópnir", "Wanyūdō", "Warak ngendog", "Warg", "Warlock",
    "Wati-kutjara", "Wekufe", "Wendigo", "Werecat", "Werehyena", "Werewolf",
    "Wild man", "Wirry-cow", "Witte Wieven", "Wolpertinger", "Wulver", "Wyvern",
    "Xana", "Xelhua", "Xhindi", "Xiuhcoatl", "Yacumama", "Yacuruna",
    "Yadōkai", "Yaksha", "Yakshini", "Yakshini", "Yama", "Yama-bito",
    "Yama-uba", "Yamata no Orochi", "Yaoguai", "Yara-ma-yha-who", "Yato-no-kami", "Yeti",
    "Ypotryll", "Yuki-onna", "Yuxa", "Yōkai", "Yōsei", "Yūrei",
    "Zahhak", "Zashiki-warashi", "Zduhać", "Zennyo Ryūō", "Zeus", "Zilant",
    "Ziz", "Zmeu", "Zombie", "Zuijin", "Zână"]


adjective_list = [
    "Olympian", "abhorrence", "abominable", "accurate", "accursed", "actual",
    "additional", "advanced", "afterlife", "agitation", "alarm", "american",
    "ancient", "angelic", "angelic", "angst", "annihilation", "antitank",
    "anxiety", "anxiety", "appropriate", "astral", "atomic", "atrocious",
    "atrocious", "automatic", "available", "aversion", "awe", "awe",
    "awesome", "awful", "barbarous", "barbarous", "basic", "beatific",
    "beautiful", "believing", "bereavement", "best", "bestial", "better",
    "big", "biggest", "biological", "bitter", "bladed", "blessed",
    "blessed", "bloodthirsty", "bloody", "blunt", "broken", "brutal",
    "brutish", "bête noire", "caliber", "callous", "carnal", "casualty",
    "celestial", "certain", "cessation", "chaste", "chemical", "chickenheartedness",
    "chief", "clean", "clumsy", "cold feet", "cold sweat", "cold-blooded",
    "common", "competitive", "concealed", "concern", "consecrated", "consternation",
    "consternation", "controversial", "convenient", "conventional", "cowardice", "creeps",
    "critical", "crude", "cruel", "cruel", "curtains", "customary",
    "damnable", "damned", "dangerous", "darkness", "deadliest", "deadly",
    "decease", "decisive", "dedicated", "defensive", "degenerate", "demise",
    "demoniac", "demonic", "departure", "depraved", "despair", "destruction",
    "destructive", "devastating", "devilish", "devoted", "devotional", "devout",
    "diabolical", "different", "discomposure", "dismay", "dismay", "disquietude",
    "dissolution", "distress", "divine", "divine", "doubt", "downfall",
    "drawn", "dread", "dread", "dreadful", "dying", "economic",
    "edged", "effective", "effectual", "efficient", "elysian", "empty",
    "empyral", "empyrean", "end", "ending", "eradication", "essential",
    "eternal", "eternal rest", "ethereal", "euthanasia", "evil", "excellent",
    "excruciating", "execution", "exit", "expiration", "extermination", "extinction",
    "faintheartedness", "faithful", "fallen", "familiar", "fatal", "fatality",
    "faultless", "favored", "favorite", "favourite", "fearful", "fearfulness",
    "fearsome", "ferocious", "fierce", "fighting", "final", "fine",
    "finis", "finish", "first", "flinty", "foreboding", "formidable",
    "fright", "fright", "funk", "german", "glorified", "god-fearing",
    "godlike", "godlike", "godly", "good", "good", "grave",
    "great", "greatest", "grim reaper", "hallowed", "hallowed", "handy",
    "hard", "hard-hearted", "harsh", "hateful", "heartless", "heaven",
    "heavier", "heavy", "hellish", "hidden", "holstered", "holy",
    "holy", "horrible", "horror", "horror", "huge", "human",
    "humble", "ideal", "ideological", "illegal", "immaculate", "immortal",
    "implacable", "important", "indispensable", "inexorable", "inferior", "infernal",
    "inhuman", "inhumane", "innocent", "intimidation", "invincible", "irresistible",
    "jitters", "just", "keen", "key", "large", "laser",
    "last", "latter", "legal", "legitimate", "lethal", "light",
    "like", "little", "loaded", "long", "looking", "loss",
    "made", "magic", "magical", "main", "major", "makeshift",
    "malevolent", "martyrdom", "massive", "merciless", "messianic", "mightiest",
    "mighty", "military", "misgiving", "modern", "monstrous", "monstrous",
    "moral", "more", "mortality", "murderous", "naked", "national",
    "natural", "nearest", "necessary", "necrosis", "nefarious", "new",
    "next", "nightmare", "nuclear", "obliteration", "oblivion", "offensive",
    "old", "only", "ordinary", "other", "otherworldly", "own",
    "painful", "panic", "panic", "paradise", "particular", "parting",
    "passing", "passing over", "peculiar", "perfect", "perfect", "pernicious",
    "personal", "phobia", "pietistic", "pious", "poignant", "pointed",
    "political", "ponderous", "poor", "popular", "possible", "potent",
    "potential", "powerful", "prayerful", "preferred", "presentiment", "primary",
    "primitive", "principal", "proper", "psychological", "pure", "qualm",
    "quietus", "radiological", "rancorous", "range", "ready", "real",
    "recreancy", "release", "relentless", "reliable", "repose", "revengeful",
    "revered", "reverence", "reverent", "revulsion", "rhetorical", "right",
    "righteous", "rude", "ruin", "ruination", "ruthless", "sacred",
    "sacrosanct", "sadistic", "sainted", "saintlike", "saintly", "same",
    "sanctified", "satanic", "scare", "second", "secret", "semiautomatic",
    "seraphic", "seraphic", "serviceable", "shaped", "sharp", "sharpest",
    "shock", "silence", "similar", "simple", "sinful", "single",
    "sleep", "small", "sole", "special", "specific", "spiritual",
    "spiritual", "spiritual", "spiteful", "splendid", "spotless", "standard",
    "strange", "strategic", "strong", "strongest", "sublime", "sublime",
    "successful", "such", "suffering", "suitable", "superior", "supernal",
    "supernatural", "supernatural", "sure", "suspicion", "tactical", "tank",
    "termination", "terrible", "terrible", "terror", "terrorist", "thermonuclear",
    "third", "timidity", "tomb", "torture", "traditional", "transcendental",
    "transmundane", "trembling", "tremendous", "tremor", "trepidation", "trepidation",
    "trepidity", "true", "tyrannical", "ultimate", "uncorrupt", "undefiled",
    "unease", "uneasiness", "unfeeling", "unique", "unkind", "unnatural",
    "unrelenting", "untainted", "unusual", "unworldly", "uplifted", "upright",
    "useful", "useless", "usual", "valuable", "venerable", "venerated",
    "vengeful", "very", "vicious", "vicious", "virtuous", "virulent",
    "warlike", "wicked", "wicked", "wooden", "worry"]

